apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::082706807015:role/DevSecOps-Cluster-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::082706807015:role/DevSecOps-Jenkins-Role
      username: jenkins
      groups:
        - system:masters
